#####################################
# swarm에서 작동하는 docker-compose
#####################################
version: '3.8'

########################### SERVICES
services:
  wordpress:
    image: ghcr.io/hansanghyeon/wordpress-redis:5.8.2-php8.0-apache-redis
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', '${TYPE}-${PROJECT_NAME}_redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
    volumes:
      - wordpress:/var/www/html
      - ./app/wp/wp-content:/var/www/html/wp-content
      - ./app/wp/src:/var/www/html/wp-content/themes/headless
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        ## HTTP Routers
        - traefik.http.routers.${TYPE}_${PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.${TYPE}_${PROJECT_NAME}.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${TYPE}_${PROJECT_NAME}.tls.certresolver=leresolver
        - traefik.http.services.${TYPE}_${PROJECT_NAME}.loadbalancer.server.port=80
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wp
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./.mysql:/var/lib/mysql
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}

########################### NETWORKS
networks:
  default:
    external:
      name: proxy-main
volumes:
  redis:
  wordpress:
