version: '3.8'

########################### SERVICES
services:
  wordpress:
    image: ghcr.io/hansanghyeon/wordpress-xdebug:pre-alpha-v0.0.2
    restart: always
    networks:
      - traefik
      - default
    env_file:
      - ./.env
      - ./.env.minio
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
        define('AS3CF_SETTINGS', serialize(
          array( 
            'provider' => 'aws', 
            'access-key-id' => getenv_docker('MINIO_ROOT_USER', ''),
            'secret-access-key' => getenv_docker('MINIO_ROOT_PASSWORD', ''),
          )
        ));
    volumes:
      - ./.docker/wp:/var/www/html
      - ./apps/theme:/var/www/html/wp-content/themes/main
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.${TYPE}-201912-${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${TYPE}-201912-${PROJECT_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${TYPE}-201912-${PROJECT_NAME}.tls.certresolver=leresolver
      - traefik.http.services.${TYPE}-201912-${PROJECT_NAME}.loadbalancer.server.port=80
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./.docker/db/data:/var/lib/mysql
  redis:
    image: redis:latest
    volumes:
      - redis:/data
  minio:
    image: minio/minio
    volumes:
      - ./.docker/minio/data/minio_root:/minio_root:z
      - ./.docker/minio/data/certs:/root/.minio/certs:z
    networks:
      - traefik
      - default
    env_file:
      - ./.env
      - ./.env.minio
    command: minio server /minio_root --console-address ":9001"
    labels:
      - traefik.enable=true
      # console
      - traefik.http.routers.${TYPE}-201912-minio-${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${TYPE}-201912-minio-${PROJECT_NAME}.rule=Host(`${CDN_DOMAIN}`)
      - traefik.http.routers.${TYPE}-201912-minio-${PROJECT_NAME}.tls.certresolver=leresolver
      - traefik.http.routers.${TYPE}-201912-minio-${PROJECT_NAME}.service=${TYPE}-201912-minio-${PROJECT_NAME}-service
      - traefik.http.services.${TYPE}-201912-minio-${PROJECT_NAME}-service.loadbalancer.server.port=9001
      # api
      - traefik.http.routers.${TYPE}-201912-minio-${PROJECT_NAME}-api.entrypoints=websecure
      - traefik.http.routers.${TYPE}-201912-minio-${PROJECT_NAME}-api.rule=Host(`${CDN_DOMAIN}`) && PathPrefix("/wordpress")
      - traefik.http.routers.${TYPE}-201912-minio-${PROJECT_NAME}-api.tls.certresolver=leresolver
      - traefik.http.routers.${TYPE}-201912-minio-${PROJECT_NAME}-api.service=${TYPE}-201912-minio-${PROJECT_NAME}-api-service
      - traefik.http.services.${TYPE}-201912-minio-${PROJECT_NAME}-api-service.loadbalancer.server.port=9000

########################### NETWORKS
networks:
  traefik:
    external:
      name: traefik_proxy
volumes:
  redis:
