version: '3.8'

########################### SERVICES
services:
  wordpress:
    image: wordpress:6.0.2-php8.0-apache
    restart: always
    networks:
      - traefik
      - default
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
        define('WP_MEMORY_LIMIT', '128M');
    volumes:
      - ./.docker/wp/wp-content:/var/www/html/wp-content
      - ./apps/theme:/var/www/html/wp-content/themes/main
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=leresolver
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=80
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./.docker/db/data:/var/lib/mysql
  redis:
    image: redis:latest
    volumes:
      - redis:/data

########################### NETWORKS
networks:
  traefik:
    external:
      name: traefik_proxy
volumes:
  redis:
