name: ğŸš› (release test) static code deploy
on:
  push:
    branches: [release/*]
    paths:
      - "Theme/resources/views/**/*"
      - "Theme/resources/fonts/**/*"
      - "Theme/resources/images/**/*"
      - "Theme/resources/video/**/*"

jobs:
  source:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.name == 'peterosea' }}
    name: ğŸ“® Github ì†ŒìŠ¤ì½”ë“œë¡œ ì—…ë°ì´íŠ¸ `git checkout release/* && git pull origin release/*`
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOYSERVER_KEY }}
          host: ${{ secrets.DEPLOYSERVER_HOST }}
          username: ${{ secrets.DEPLOYSERVER_USERNAME }}
          port: ${{ secrets.DEPLOYSERVER_PORT }}
          script: |
            cd www
            git fetch origin
            git checkout ${GITHUB_REF##*/}
            git pull origin ${GITHUB_REF##*/}
