name: ğŸ™†â€â™‚ï¸ ìˆ˜ë™ static & build code deploy
on:
  workflow_dispatch:

jobs:
  source:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.name == 'Hansanghyeon' }}
    name: ğŸ“® Github ì†ŒìŠ¤ì½”ë“œë¡œ ì—…ë°ì´íŠ¸ `git pull origin main`
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOYSERVER_KEY }}
          host: ${{ secrets.DEPLOYSERVER_HOST }}
          username: ${{ secrets.DEPLOYSERVER_USERNAME }}
          port: ${{ secrets.DEPLOYSERVER_PORT }}
          script: |
            cd ./@project/${{ secrets.PROJECT_DIR }}
            git fetch origin
            git checkout main
            git branch | grep 'release/*' | xargs git branch -D
            git pull origin main

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.name == 'Hansanghyeon' }}
    name: ğŸ—³ Theme source build & rsync
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        working-directory: ${{ env.working-directory }}
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ env.working-directory }}/node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: ğŸ— setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        if: ${{steps.yarn-cache.outputs.cache-hit}} != 'true'
        working-directory: ${{ env.working-directory }}
        run: |
          cd Theme
          yarn install
      - name: ğŸ”¨ yarn install & build
        run: |
          cd Theme
          yarn build:production

      - name: ğŸ“‚ Sync files to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOYSERVER_KEY }}
          SERVER_PORT: ${{ secrets.DEPLOYSERVER_RSYNC_PORT }}
          SERVER_IP: ${{ secrets.DEPLOYSERVER_HOST }}
          USERNAME: ${{ secrets.DEPLOYSERVER_USERNAME }}
          FOLDER: "./Theme/public"
          ARGS: "-rltgoDzvO --ignore-times"
          SERVER_DESTINATION: "/volume1/docker/@project/${{ secrets.PROJECT_DIR }}/Theme"
