name: ğŸ“¦ ë¦´ë¦¬ì¦ˆ
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # ìˆ˜ë™ìœ¼ë¡œ ì‹¤í–‰í• ìˆ˜ìˆë„ë¡ ì„¤ì •
    inputs:
      version_parameter:
        description: 'ë¦´ë¦¬ì¦ˆí•  ë²„ì „ì„ ì…ë ¥í•´ì£¼ì„¸ìš”. (ex. 1.0.0)'
        required: true
jobs:
  is-release:
    name: ğŸš€ ë¦´ë¦¬ì¦ˆ ì²´í¬
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version_name.outputs.version }}
      is_release: ${{ steps.is_release.outputs.is_release }}
    steps:
      - uses: actions/checkout@v2
      - name: ë²„ì „ ì •ë³´ ì¶”ì¶œ
        id: extract_version_name
        env:
          VERSION: ${{ inputs.version_parameter }}
        run: |
          if [ -n "$VERSION" ]; then
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "version=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> "$GITHUB_OUTPUT"
          fi
      # extract_version_nameì— ë²„ì „ì´ ì—†ë‹¤ë©´ ë¦´ë¦¬ì¦ˆê°€ ì•„ë‹˜
      # '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' ì´ë¶€ë¶„ì€ ë²„ì „ì„ ì¶”ì¶œí•˜ëŠ” ì •ê·œì‹
      # í•´ë‹¹ì •ê·œì‹ì— ë§ëŠ” ê°’ì´ ë‚˜ì™”ë‹¤ë©´ ë‹¤ìŒ jobì„ ì‹¤í–‰í• ìˆ˜ìˆë„ë¡ trueë¥¼ ë°˜í™˜
      - name: ë¦´ë¦¬ì¦ˆ ì²´í¬
        id: is_release
        run: |
          if [[ -z "${{ steps.extract_version_name.outputs.version }}" ]]; then
            echo "is_release=false" >> "$GITHUB_OUTPUT"
          else
            echo "is_release=true" >> "$GITHUB_OUTPUT"
          fi
  
  check-env:
    name: ğŸ” ì•¡ì…˜ ì»¤ìŠ¤í…€ ì „ì—­ë³€ìˆ˜ í™•ì¸
    runs-on: ubuntu-latest
    needs: [is-release]
    steps:
      - name: Check env
        run: |
          echo "version=${{ needs.is-release.outputs.version }}"
          echo "is_release=${{ needs.is-release.outputs.is_release }}"
      - name: Check input
        env:
          VERSION: ${{ inputs.version_parameter }}
        run: |
          echo "VERSION=$VERSION"

  # ì‚¬ì „ ê²€ì‚¬ ë ì§„ì§œ ë¹Œë“œ ì‹œì‘
  theme-build:
    name: ğŸ— í…Œë§ˆ ë¹Œë“œ
    needs: [is-release]
    if: ${{ needs.is-release.outputs.is_release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— setup-node (v18.x)
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: node_modules ìºì‹± (cache node_modules)
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: node_modules ì„¤ì¹˜ (node_modules install)
        run: yarn install --frozen-lockfile --prefer-offline --no-progress
        if: steps.cache.outputs.cache-hit != 'true'

      - name: ğŸ”¨ (node dependencies) monorepo yarn install
        run: |
          yarn install && cd theme && yarn install

      - name: ğŸ”¨ (node dependencies) bootstrap
        run: |
          Make bootstrap

      - name: ğŸ“¦ install, build
        run: |
          Make build

      # Caching dependencies for faster builds
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: ğŸ”¨ (php dependencies) php composer install
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          args: --working-dir=./theme
          command: install
          
      # themeíŒŒì¼ì„ ì••ì¶•í•˜ê¸°ì „ì— node_modulesì œê±°
      - name: ğŸ“¦ theme remove node_modules
        run: |
          cd theme
          rm -rf node_modules

      # themeí´ë”ë¥¼ ì••ì¶•í•˜ì—¬ artifactë¡œ ì €ì¥
      - name: ğŸ“¦ theme zip
        run: |
          zip -r theme.zip theme

      - uses: actions/upload-artifact@v2
        with:
          name: theme-buile-result
          path: ./theme.zip

  release:
    runs-on: ubuntu-latest
    name: ğŸš› ë¦´ë¦¬ì¦ˆ, ì›Œë“œí”„ë ˆìŠ¤ í…Œë§ˆ íŒŒì¼ì—…ë¡œë“œ
    needs: [is-release, theme-build]
    if: ${{ needs.is-release.outputs.is_release == 'true' }}
    outputs:
      release_url: ${{ steps.create_release.outputs.html_url }}
    steps:
      - uses: actions/checkout@v2

      # buildì˜ ì•„í‹°í™íŠ¸ ê³µìœ 
      - uses: actions/download-artifact@v2
        with:
          name: theme-buile-result
          path: ./

      - name: Release ìƒì„±
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ needs.is-release.outputs.version }}
          release_name: ${{ needs.is-release.outputs.version }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: theme.zip
          asset_name: theme.zip
          asset_content_type: application/zip

  noti:
    name: ğŸ¦… ë¹Œë“œ ê²°ê³¼ ë…¸í‹°
    needs: [theme-build, release, is-release]
    if: ${{ needs.is-release.outputs.is_release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            # [${{ needs.is-release.outputs.version }}][${{ github.repository }}] ë¦´ë¦¬ì¦ˆ ë°°í¬ ì™„ë£Œ
            author: ${{ github.actor }}
            ë¦´ë¦¬ì¦ˆ: ${{ needs.release.outputs.release_url }}